---
- name: Create Caddy directories
  file:
    path: "{{ item }}"
    owner: "{{ caddy_host_user }}"
    group: "{{ caddy_host_group }}"
    state: directory
  loop:
    - "{{ caddy_host_dir }}"
    - "{{ caddy_host_data_dir }}"

- name: Create Docker networks
  docker_network:
    name: "{{ item.name }}"
  loop: "{{ caddy_container_networks }}"
  when: caddy_create_networks | bool

- name: Start Caddy Docker Proxy
  docker_container:
    name: "{{ caddy_container_name }}"
    image: "{{ caddy_image }}"
    restart_policy: "{{ caddy_container_restart_policy }}"
    volumes: "{{ caddy_container_volumes }}"
    env: "{{ caddy_container_env_vars }}"
    published_ports: "{{ caddy_container_ports }}"
    networks: "{{ caddy_container_networks }}"
    labels: "{{ caddy_container_labels }}"
    detach: true
    state: "{{ caddy_container_state }}"
  notify:
    - Restart Caddy
