---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: "ghcr.io/mrsuicideparrot/molecule-docker:latest"
    command: "molecule test"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible

verifier:
  name: ansible
