---
name: Release
on:
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: 'obvionaoe.caddy'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo.
        uses: actions/checkout@v2
        with:
          path: 'obvionaoe.caddy'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy.
        run: >-
          ansible-galaxy role import --token ${{ secrets.ANSIBLE_GALAXY_TOKEN }} --branch ${{ github.ref_name }} ${{ github.repository_owner }} ${{ github.event.repository.name }}

      - name: Release
        uses: softprops/action-gh-release@v2
